new ru translation file for Model Generation
modxorg/Docs pull request #195
Opened 2020-02-20 22:08 UTC by himurovich

2020-02-21 02:07 UTC, Ibochkarev requested changes

2020-02-21 02:07 UTC, Ibochkarev commented on ru/extending-modx/xpdo/custom-models/generating-the-model.md
> +``` php
Мне кажется тут нужно делать 3 блока кода, а не один.

2020-03-16 03:28 UTC, Ibochkarev requested changes

2020-03-16 03:28 UTC, Ibochkarev commented on ru/extending-modx/xpdo/custom-models/validation/index.md
> +_old_uri: "2.x/advanced-features/object-validation"
```suggestion
title: "Валидация объектов"
translation: "extending-modx/xpdo/custom-models/validation "
```

2020-03-16 16:47 UTC, ant-tar commented on ru/extending-modx/xpdo/custom-models/generating-the-model.md
> +``` php
Чисто стилистически и для нужд документации? Возможно, но речь идет о переопределении трех переменных,
фактически это можно сделать в рамках одного php кода.

```
$generator->classTemplate = ...
$generator->platformTemplate = ..
$generator->mapHeader= ...
```

2020-03-16 16:47 UTC, ant-tar commented on ru/extending-modx/xpdo/custom-models/generating-the-model.md
> +``` php
@Ibochkarev привет, Иван! хотел бы закрыть этот гештальт) таки почему ты считаешь, что три блока надо?

2020-03-16 16:51 UTC, merged