Shorten the FileDownloadR documentation
modxorg/Docs pull request #461
Opened 2023-06-20 07:11 UTC by Jako

## Description

Shorten the documentation here and maintain it on GitHub pages in the extra repository. This way, the documentation only needs to be kept up to date once.

2023-06-20 07:16 UTC, Ibochkarev approved these changes

2023-06-20 07:16 UTC, Ibochkarev commented on en/extras/filedownload-r/index.md
> +Repository, available on https://modx.com/extras/package/filedownloadr
```suggestion
Repository, available on [filedownloadr](https://modx.com/extras/package/filedownloadr)
```

2023-06-20 07:16 UTC, Ibochkarev commented on en/extras/filedownload-r/index.md
> +https://github.com/Jako/FileDownloadR/issues
```suggestion
[issues](https://github.com/Jako/FileDownloadR/issues)
```

2023-06-20 07:16 UTC, Ibochkarev commented on en/extras/filedownload-r/index.md
> +FileDownloadR has a GitHub repository at https://github.com/Jako/FileDownloadR. Any bug can be issued on
```suggestion
FileDownloadR has a GitHub repository at [FileDownloadR](https://github.com/Jako/FileDownloadR). Any bug can be issued on 
```

2023-06-20 07:16 UTC, Ibochkarev commented on en/extras/filedownload-r/index.md
> +The package documentation can be found at http://jako.github.io/FileDownloadR/
```suggestion
The package documentation can be found at [FileDownloadR](http://jako.github.io/FileDownloadR/)
```

2023-06-20 07:19 UTC, Ibochkarev requested changes

2023-06-20 07:19 UTC, Ibochkarev commented on en/extras/filedownload-r/index.md
> +FileDownload Evolution package by Kyle Jaebker. It is maintained since 2023 by Thomas Jakobi(https://github.com/Jako).
```suggestion
FileDownload Evolution package by Kyle Jaebker. It is maintained since 2023 by [Thomas Jakobi](https://github.com/Jako).
```

2023-06-20 07:20 UTC, merged

2023-06-20 11:11 UTC, Mark-H commented
As this deletes files, can we get some redirects for those deleted pages so we don't start serving up 404s?

2023-06-20 16:26 UTC, Jako commented
This has to be handled in the Docs app. Some table that has source/target redirects.

2023-06-20 16:58 UTC, Mark-H commented
No, that's in this repo: https://github.com/modxorg/Docs/blob/2.x/redirects.json

2023-06-20 17:18 UTC, Jako commented
Thanks for the information. Done in #466

2023-07-08 21:28 UTC, Jako commented
It seems that the changes in the repository are not visible on https://docs.modx.com/2.x/en/extras/filedownload-r